### ISSUE TITLE
ReferenceError: i is not defined

### ISSUE THREAD

**Issue by mradenovic** [variadicjs/variadicjs.github.io#28] opened 2018-02-18 01:38 UTC
`populationStandardDeviation` and `sampleStandardDeviation` throw an error `ReferenceError: i is not defined` with certain parameters.

```JavaScript
variadic.populationStandardDeviation(1,2,3) = // ReferenceError: i is not defined
variadic.sampleStandardDeviation(1,2,3) = 1

variadic.populationStandardDeviation(10,10,13) = // ReferenceError: i is not defined
variadic.sampleStandardDeviation(10,10,13) = // ReferenceError: i is not defined

variadic.populationStandardDeviation(10,10,13,13) = 1.5
variadic.sampleStandardDeviation(10,10,13,13) = // ReferenceError: i is not defined

variadic.populationStandardDeviation(10,10,10,13) = // ReferenceError: i is not defined
variadic.sampleStandardDeviation(10,10,10,13) = 1.5
```

**Comment by AtlantaDancer** [comment] 2018-03-12 05:12
This is an issue with transpiling of `floatprecise` 
The original code is
```js
exports.floatPrecise = (num) => {const str = num.toString();
  // if decimal terminates, or is not decimal, or is in exponential form, return num
  if (str.length < 17 || !/\./.test(str) || /e/.test(str)) return num;

  // Reverse loop through number looking for index of last precise digit.
  // Imprecise floats typically contain a long string of 9s or 0s,
  // somtimes terminating in some other number,
  // so begin loop at second to last index.
  let i = str.length - 2;
  const imprecise = str[i] === '9' ? '9' : '0';

  while (str[i] === imprecise) i -= 1;

  // round number to index of last precise digit
  return parseFloat(num.toPrecision(i));
};
```
but when pulled from npm it looks like
```js
exports.floatPrecise=function(a){
    var b=a.toString();
    if(17>b.length||!/\./.test(b)||/e/.test(b))
        
    return a;
    for(var c=b.length-2,d='9'===b[c]?'9':'0';b[c]===d;)
        c-=1;
        return parseFloat(a.toPrecision(i))
    };
```
Note that the final return the `toPrecision(i)` should be 'toPrecision(c)`

I'm not sure what transpiler is causing this because when I do a build it still has comments.  It hasn't minified or uglified the code.

**Comment by jhowardjr** [comment] 2018-03-12 09:49
```npm run build``` should put the transpiled files in a dist folder of the root directory. Is that not happening?

**Comment by AtlantaDancer** [comment] 2018-03-12 10:55
It does but on my system it looks like this
```js
'use strict';

exports.floatPrecise = function (num) {
  var str = num.toString();

  // if decimal terminates, or is not decimal, or is in exponential form, return num
  if (str.length < 17 || !/\./.test(str) || /e/.test(str)) return num;

  // Reverse loop through number looking for index of last precise digit.
  // Imprecise floats typically contain a long string of 9s or 0s,
  // somtimes terminating in some other number,
  // so begin loop at second to last index.
  var i = str.length - 2;
  var imprecise = str[i] === '9' ? '9' : '0';

  while (str[i] === imprecise) {
    i -= 1;
  } // round number to index of last precise digit
  return parseFloat(num.toPrecision(i));
};
```
It doesn't match the obfuscation and comment removal that it looks like when retrieved via npm.

**Comment by jhowardjr** [comment] 2018-03-12 11:43
I see. What OS are you using?

**Comment by AtlantaDancer** [comment] 2018-03-12 14:33
I am using windows 10.  Originally the build script didn't work for me.  Said "BABEL_ENV" is not a recognized command or file.  I found "cross-env" and used it to set the environment variable.  Originally I had 
> "build": "cross-env-shell BABEL_ENV=production babel index.js -d dist && babel lib/ -d dist/lib"

but the babel for lib directory wasn't getting minified like index.js.  I couldn't get babel to do a "debug" output for it's settings, but have since confirmed this was the case.  I then changed the build script to

> "build": "cross-env BABEL_ENV=production babel index.js -d dist && cross-env BABEL_ENV=production babel lib/ -d dist/lib"

This then reproduces the original issue for variadic.js `floatprecise`.  So it does seem to be an issue with the `floatprecise` function being minified by babel.  I may play around and see if I can get a version to go through babel correctly.  May investigate reporting an issue with babel.

**Comment by AtlantaDancer** [comment] 2018-03-12 23:35
It looks like this is an issue with minify and babel.  The minify issue is 485 & 801
https://github.com/babel/minify/pull/713
https://github.com/babel/minify/issues/801
The babel issue is 4818
https://github.com/babel/babel/issues/4818
It was discussed 12 days ago, but no ETA on a fix.  It was supposed to be fixed in minify 0.30 but it isn't.

**Comment by rykdesjardins** [comment] 2018-05-06 23:19
Hello,

I saw you referenced the issue I submitted https://github.com/babel/minify/issues/801 in this issue #28. Simply wanted to let you know it was fixed, and you should be able to minify your build without any problem now. At least, all my minified builds are now fully working, and hopefully yours as well. 

Cheers 🎉

**Comment by amr08** [comment] 2018-05-18 01:03
@AtlantaDancer @jhowardjr  Closing issue per follow up message above^

**Closed by amr08** 2018-05-18 01:03 UTC
